### ISSUE TITLE
The letter 'í' is not inverted

### ISSUE THREAD

**Issue by antononcube** [lizmat/Acme-Text-UpsideDown#2]
The letter 'í' is not inverted: 

```shell
> ud por ahí
íɥɐ ɹod
```

**Comment by lizmat** [comment]
Is this in the right repo?

**Comment by lizmat** [comment]
That's because `í` is not a supported character (at least not at the moment).  And unsupported characters are just passed through.  If you use an `i`, you will see it *does* work:
````
$ ud ud por ahi
ᴉɥɐ ɹod pn
````
I'd be happy to accept a PR with any characters you'd like to see supported (and their counterparts of course) as long as there is a 1-to-1 relation between the characters.
